title: 'TJHSST SGA'
default_lang: en
author:
  name: SGA
  email: sga.tjhsst@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Official website for TJHSST''s Student Government Association.'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
